version: '3.8'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_PASSWORD=mysecretpassword
      - CASSANDRA_USER=cassandra

volumes:
  cassandra_data: